CONFIG_ZMK_KEYBOARD_NAME="Kruse36"
CONFIG_BT_DEVICE_NAME="Kruse36"
# CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=n

# increase bluetooth signal power
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Enable split
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE=y

# Enable mouse / pointing
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y

# enable deep sleep support
CONFIG_ZMK_SLEEP=y

# the keyboard disconnects from bluetooth.
# uses very little power, but it may take
# a few seconds to reconnect after waking.
# 1.800.000 ms = 30 minutes
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

# "Eager Debouncing"
# Trying to lower the input lag.
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5

# Uncomment to create a firmware that clears all bluetooth bonds on startup.
# Don't leave this way though as the keyboard will forget all paired devices every time it restarts.
# CONFIG_ZMK_BLE_CLEAR_BONDS_ON_START=y

